---
- name: Ensure repos directory exists
  ansible.builtin.file:
    path: "{{ vulnbox_repos_dir }}"
    state: directory
    mode: '0755'

- name: Download socat-plus
  ansible.builtin.git:
    repo: https://github.com/CCTorVergata/socat-plus
    dest: "{{ vulnbox_repos_dir }}/socat-plus"
    force: true

- name: Check if the firegex container is already running
  community.docker.docker_container_info:
    name: firegex
  register: firegex_info
  changed_when: false

- name: Setup firegex
  include_tasks: "setup-firegex.yml"
  when: not firegex_info.exists
