---
- name: Download socat-plus
  ansible.builtin.git:
    repo: https://github.com/CCTorVergata/socat-plus
    dest: /root/socat-plus
    force: true

- name: Setup firegex
  include_tasks: "setup-firegex.yml"
