- name: "Create docker folder in /srv"
  file:
    path: "/srv/docker"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
  become: true

- name: "Clone flagwarehouse"
  git:
    repo: https://github.com/CCTorvergata/flagWarehouse.git
    dest: /srv/docker/flagwarehouse
    force: true

- name: "Build and start flagWarehouse"
  community.docker.docker_compose_v2:
    project_src: /srv/docker/flagwarehouse
    build: always

- name: "Clone tulip"
  git:
    repo: https://github.com/CCTorvergata/tulip.git
    dest: /srv/docker/tulip
    force: true

- name: "Build and start Tulip container"
  community.docker.docker_compose_v2:
    project_src: /srv/docker/tulip
    build: always

- name: "Clone AODashboard"
  git:
    repo: https://github.com/CCTorvergata/AODashboard.git
    dest: /srv/docker/dashboard
    force: true

- name: "Build and start AODashboard container"
  community.docker.docker_compose_v2:
    project_src: /srv/docker/dashboard
    build: always

- name: "Copying get-traffic.sh"
  copy:
    src: files/client/get-traffic.sh
    dest: /usr/local/sbin/get-traffic.sh
    owner: root
    group: root
    mode: '0755'
  become: true

- name: "Copying get-traffic.service"
  copy:
    src: files/client/get-traffic.service
    dest: /usr/lib/systemd/system/get-traffic.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload systemd services
  systemd_service:
    daemon_reload: true

- name: Enable and start get-traffic.service
  ansible.builtin.systemd_service:
    name: get-traffic.service
    state: started
    enabled: true
  become: true
