---
- name: Create traffic folder in /srv
  ansible.builtin.file:
    path: "/srv/traffic"
    state: directory
    mode: '0755'
    owner: root
  become: true

- name: Copying get-traffic.sh
  ansible.builtin.template:
    src: get-traffic.sh.j2
    dest: /usr/local/sbin/get-traffic.sh
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Copying get-traffic.service
  ansible.builtin.copy:
    src: get-traffic.service
    dest: /etc/systemd/system/get-traffic.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable and start get-traffic.service
  ansible.builtin.systemd_service:
    name: get-traffic.service
    state: started
    enabled: true
    daemon_reload: true
  become: true
