---
- name: "Set up vulnbox"
  hosts: vulnbox
  roles:
    - vulnbox/copy-ssh-public-keys
    - vulnbox/install-requirements
    - vulnbox/setup-sniffer
    - vulnbox/targz-services
    - vulnbox/setup-repos
    - vulnbox/bash-aliases


- name: "Set up services for Attack and Defense CTF"
  hosts: localhost
  connection: local
  roles:
    - client/setup-get-traffic
    - client/start-docker
    - client/setup-repos
