---
- name: Create docker folder in /srv
  ansible.builtin.file:
    path: "{{ client_repos_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_facts['env']['USER'] }}"
  become: true

- name: Clone flagwarehouse
  ansible.builtin.git:
    repo: https://github.com/CCTorvergata/flagWarehouse.git
    dest: "{{ client_repos_dir }}/flagwarehouse"
    force: true

- name: Clone tulip
  ansible.builtin.git:
    repo: https://github.com/CCTorvergata/tulip.git
    dest: "{{ client_repos_dir }}/tulip"
    force: true

- name: Clone AODashboard
  ansible.builtin.git:
    repo: https://github.com/CCTorvergata/AODashboard.git
    dest: "{{ client_repos_dir }}/dashboard"
    force: true

- name: Build and start AODashboard container
  community.docker.docker_compose_v2:
    project_src: "{{ client_repos_dir }}/dashboard"
    build: always
  become: true
