---
- name: Create docker folder in /srv
  ansible.builtin.file:
    path: "/srv/docker"
    state: directory
    mode: '0755'
    owner: "{{ ansible_facts['env']['USER'] }}"
  become: true

- name: Clone flagwarehouse
  ansible.builtin.git:
    repo: https://github.com/CCTorvergata/flagWarehouse.git
    dest: /srv/docker/flagwarehouse
    force: true

- name: Clone tulip
  ansible.builtin.git:
    repo: https://github.com/CCTorvergata/tulip.git
    dest: /srv/docker/tulip
    force: true

- name: Clone AODashboard
  ansible.builtin.git:
    repo: https://github.com/CCTorvergata/AODashboard.git
    dest: /srv/docker/dashboard
    force: true

- name: Build and start AODashboard container
  community.docker.docker_compose_v2:
    project_src: /srv/docker/dashboard
    build: always
  become: true
