---
- name: Install requirements
  ansible.builtin.apt:
    name:
      - rsync
      - tshark
      - tmux
      - git
      - sudo
      - vim
      - nano
      - htop
      - tree
      - ripgrep
      - python3-requests
    state: present
    update_cache: true
