---
- name: Create ssh-key
  ansible.builtin.openssh_keypair:
    path: "{{ playbook_dir }}/out/id_rsa_cc"
    type: rsa
    size: 2048
    force: true
  delegate_to: localhost
  run_once: true

- name: Copy ssh key on the vulnbox
  ansible.builtin.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '../out/id_rsa_cc.pub') }}"

- name: Ensure tcpdump is installed
  ansible.builtin.apt:
    name: tcpdump
    state: present
    update_cache: true

- name: Copy sniffer.sh
  ansible.builtin.copy:
    src: files/sniffer.sh
    dest: /usr/local/sbin/sniffer.sh
    owner: root
    group: root
    mode: '0755'

- name: Copy sniffer.service
  ansible.builtin.copy:
    src: files/sniffer.service
    dest: /usr/lib/systemd/system/sniffer.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start sniffer.service
  ansible.builtin.systemd_service:
    name: sniffer.service
    state: started
    enabled: true
    daemon_reload: true

- name: Download firegex
  ansible.builtin.git:
    repo: https://github.com/Pwnzer0tt1/firegex
    dest: /root/firegex
    force: true

- name: Generate password for firegex
  ansible.builtin.set_fact:
    password_firegex: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"

- name: Print firegex password on a file
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/out/password_firegex.txt"
    content: "{{ password_firegex }}"
    mode: "0644"
  delegate_to: localhost
  run_once: true

- name: Start firegex
  ansible.builtin.command: "python3 start.py start --port 49123 --startup-psw {{ password_firegex }}"
  args:
    chdir: /root/firegex

- name: Download socat-plus
  ansible.builtin.git:
    repo: https://github.com/CCTorVergata/socat-plus
    dest: /root/socat-plus
    force: true
