---
- name: Check if .tar.gz already exists
  ansible.builtin.stat:
    path: /root/services.tar.gz
  register: services_targz

- name: Check for directories in /root
  ansible.builtin.find:
    paths: /root
    file_type: directory
  register: root_contents

- name: Create .tar.gz if there are directories to compress (only once)
  include_tasks: "targz-services.yml"
  when: (root_contents.files | length > 0) and (not services_targz.stat.exists)
