- name: "Set up services for Attack and Defense CTF"
  hosts: localhost
  connection: local
  tasks:
    - name: "Create docker folder in /srv"
      file:
        path: "/srv/docker"
        state: directory
        mode: '0755'
        owner: "{{ ansible_env.USER }}"
      become: yes

    - name: "Clone flagwarehouse"
      git:
        repo: https://github.com/CCTorvergata/flagWarehouse.git
        dest: /srv/docker/flagwarehouse
        force: true

    - name: "Clone tulip"
      git:
        repo: https://github.com/CCTorvergata/tulip.git
        dest: /srv/docker/tulip
        force: true

    - name: "Clone AODAshboard"
      git:
        repo: https://github.com/CCTorvergata/AODashboard.git
        dest: /srv/docker/dashboard
        force: true

    - name: "Build and start AODashboard container"
      community.docker.docker_compose_v2:
        project_src: /srv/docker/dashboard
        build: always

    - name: "Copying get_traffic.sh"
      copy:
        src: files/client/get_traffic.sh
        dest: /usr/local/sbin/get_traffic.sh
        owner: root
        group: root
        mode: '0755'
      become: yes

    - name: "Copying get_traffic.service"
      copy:
        src: files/client/get_traffic.service
        dest: /usr/lib/systemd/system/get_traffic.service
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Reload systemd services
      systemd_service:
        daemon_reload: true

    - name: Enable and start get_traffic.service
      ansible.builtin.systemd_service:
        name: get_traffice.service
        state: started
        enabled: true
      become: yes

    - name: Copy start-ctf.sh
      copy:
        src: files/client/start-ctf.sh
        dest: /usr/local/sbin/start-ctf.sh
        owner: root
        group: root
        mode: '0755'
      become: yes

    - name: Copy stop-ctf.sh
      copy:
        src: files/client/stop-ctf.sh
        dest: /usr/local/sbin/stop-ctf.sh
        owner: root
        group: root
        mode: '0755'
      become: yes