- name: "Set up vulnobx"
  hosts: vulnbox
  tasks:
    - name: "Create ssh-key"
      openssh_keypair:
        path: /root/.ssh/id_rsa_cc
        type: rsa
        size: 2048
        force: false
      delegate_to: localhost
      run_once: true
      become: yes

    - name: Copy ssh key on the vulnbox
      authorized_key:
      user: "{{ remote_user }}"
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa_cc.pub') )}}"
      become: yes

    - name: Copy sniffer.sh
      copy:
        src: files/sniffer.sh
        dest: /usr/local/sbin/sniffer.sh
        owner: root
        group: root
        mode: '0755'

    - name: Copy sniffer.service
      copy:
        src: files/sniffer.service
        dest: /usr/lib/systemd/system/sniffer.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd services
      systemd_service:
        daemon_reload: true

    - name: Enable and start sniffer.service
      ansible.builtin.systemd_service:
        name: sniffer.service
        state: started
        enabled: true

    - name: Download firegex
      ansible.builtin.git:
        repo: https://github.com/Pwnzer0tt1/firegex
        dest: /root/firegex

    - name: Start firegex
      ansible.builtin.command: "python start.py start --port 49123 --startup-psw {{ lookup('file', 'files/password.txt') }}"
      args:
          chdir: /root/firegex
